<h3>Arrays:</h3>

 - It is a collection of data of same type in a contiguous memory.
 - It provides a random access to the elements stored.

In [16]:
import numpy as np
import array

In [17]:
lst = [10, 20, 30, 40, 50, 60, 70, 80, 90]
arr = np.array(lst)

In [18]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
type(arr)

numpy.ndarray

<h4>One Dimensional Array - How to find the address of an element</h4>

<pre>
Location of any element (1-D array) = Base Address + (m - l) * size of each element

where, 
m = index of the element
l = base index
</pre>

<h4>Two Dimensional Array - Row Major Order and Column Major Order</h4>

<pre>
Location of any element in (2-D array) = Base Address + [(i - lower bound of row) * nC + (j - lower bound of columns)] * size of each element

where,
i = row order location
j = column order location
</pre>

#### Operations on Array:

In [26]:
# APPEND
num = [1,2,3,4,5]
arr1 = np.array(num)
print(arr1)
# after appending
arr1 = np.append(arr1,6)
print(arr1)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [27]:
# INSERT
arr2 = np.array(num)
print(arr2)

# after inserting the value 6 at position 5
arr2 = np.insert(arr2,5,6)

print(arr2)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [28]:
# POP
# initializing array with array values
arr= array.array('i',[1, 2, 3, 1, 5])
  
# printing original array
print ("The new created array is : ",end="")
for i in range (0,5):
    print (arr[i],end=" ")
  
print("\r")
  
# using pop() to remove element at 2nd position
print ("The popped element is : ",end="")
print (arr.pop(2));
  
# printing array after popping
print ("The array after popping is : ",end="")
for i in range (len(arr)):
    print (arr[i],end=" ")

The new created array is : 1 2 3 1 5 
The popped element is : 3
The array after popping is : 1 2 1 5 

In [29]:
# remove
# initializing array with array values
arr= array.array('i',[1, 2, 3, 1, 5])
  
# printing original array
print ("The new created array is : ",end="")
for i in range (0,5):
    print (arr[i],end=" ")
  
print("\r")
  
# using remove() to remove 1st occurrence of 1
arr.remove(1)
  
# printing array after removing
print ("The array after removing is : ",end="")
for i in range (len(arr)):
    print (arr[i],end=" ")

The new created array is : 1 2 3 1 5 
The array after removing is : 2 3 1 5 

In [30]:
# index
# initializing array with array values
arr= array.array('i',[1, 2, 3, 1, 2, 5])
  
# printing original array
print ("The new created array is : ",end="")
for i in range (0,6):
    print (arr[i],end=" ")
  
print("\r")
  
# using index() to print index of 1st occurrence of 2
print ("The index of 1st occurrence of 2 is : ",end="")
print (arr.index(2))

The new created array is : 1 2 3 1 2 5 
The index of 1st occurrence of 2 is : 1


In [31]:
# reverse
# initializing array with array values
arr= array.array('i',[1, 2, 3, 1, 2, 5])
  
# printing original array
print ("The new created array is : ",end="")
for i in range (0,6):
    print (arr[i],end=" ")
  
print("\r")
  
#using reverse() to reverse the array
arr.reverse()
  
# printing array after reversing
print ("The array after reversing is : ",end="")
for i in range(len(arr)):
    print (arr[i],end=" ")

The new created array is : 1 2 3 1 2 5 
The array after reversing is : 5 2 1 3 2 1 

In [32]:
# extend
# initializing array with array values
arr1 = array.array('i',[1, 2, 3, 1, 2, 5]) 
arr2 = array.array('i',[1, 2, 3]) 
 
# using extend() to add array 2 elements to array 1 
arr1.extend(arr2)
   
print ("The modified array is : ")
for i in range (0,9):
    print (arr1[i], end=" ")

The modified array is : 
1 2 3 1 2 5 1 2 3 