<h3>Arrays:</h3>

An array is a fundamental data structure that stores a collection of elements of the same data type in contiguous memory locations. Imagine it as a row of boxes, where each box holds a value. You can access any element directly by its position (index) within the array.

<b>Key Characteristics:</b>

 - Elements of the same data type: All elements in an array must be of the same type (e.g., integers, floats, strings).
 - Contiguous memory allocation: Elements are stored sequentially in memory, allowing for efficient random access.
 - Indexing: Each element is associated with an index, starting from 0.
 - Fixed size: In most cases, the size of an array is fixed when it's created.

<h4>One Dimensional Array - How to find the address of an element</h4>

<pre>
Location of any element (1-D array) = Base Address + (m - l) * size of each element

where, 
m = index of the element
l = base index
</pre>

<h4>Two Dimensional Array - Row Major Order and Column Major Order</h4>

<pre>
Location of any element in (2-D array) = Base Address + [(i - lower bound of row) * nC + (j - lower bound of columns)] * size of each element

where,
i = row order location
j = column order location
</pre>

In [127]:
# using the array module
import array
arr = array.array('i', [10, 20, 30, 40, 50, 60, 70, 80, 90])
for i in range(0,9):
    print(arr[i], end=' ')

10 20 30 40 50 60 70 80 90 

In [128]:
type(arr)

array.array

In [129]:
# How to create an array
import numpy as np
lst = [10, 20, 30, 40, 50, 60, 70, 80, 90] #create a list
arr = np.array(lst) # using np.array convert list into array
print(arr)

[10 20 30 40 50 60 70 80 90]


In [130]:
type(arr)

numpy.ndarray

In [131]:
# Create an array filled with zeros.
arr2 = np.zeros((2, 3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [132]:
# Create an array filled with ones.
arr3 = np.ones((3, 2))
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [133]:
# Create an identity matrix of size N x N.
arr4 = np.eye(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
# Create an array with values in a specified range.
arr5 = np.arange(0, 10, 2)
arr5

array([0, 2, 4, 6, 8])

In [135]:
# Create an array with evenly spaced values over a specified range.
arr6 = np.linspace(0, 1, 5)
arr6

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### Operations on Array:

In [136]:
# Accesing Elements
# Use indexing to access elements. Indexing starts from 0.
first = arr[0]
second = arr[2]
last = arr[-1]

print(first, second, last)

10 30 90


In [137]:
# slicing in array
print(arr[2:5]) # Slice a portion of the array
print(arr[::2]) # Slice with a step
print(arr[::-1]) # reverse
print(arr[::-1][:5]) # reverse and slice

[30 40 50]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]
[90 80 70 60 50]


In [138]:
# Shape and Reshaping
arr7 = np.array([1, 2, 3, 4, 5, 6])
print("Shape and Reshaping:\n", arr7)

# Get the shape of the array
print(arr7.shape)

# Reshape the array without changing its data
print(arr7.reshape((2, 3)))

# Flatten the array to a 1D array
print(arr3.flatten())

# Transpose the array (for 2D arrays)
print(arr3.T) 

Shape and Reshaping:
 [1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
[1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [139]:
# Mathematical Operations
arr8 = np.array([10, 20, 30])
arr9 = np.array([1, 2, 3])
print("Mathematical Operations:")

# Add a value to each element.
print("arr8 + 5:", arr8 + 5)

# Subtract a value from each element.
print("arr8 - 5:", arr8 - 5)

# Multiply each element by a value.
print("arr8 * 2:", arr8 * 2)

# Divide each element by a value.
print("arr8 / 2:", arr8 / 2)

# Element-wise addition of two arrays.
print("np.add(arr8, arr9):", np.add(arr8, arr9))

# Element-wise subtraction of two arrays.
print("np.subtract(arr8, arr9):", np.subtract(arr8, arr9))

# Element-wise multiplication of two arrays.
print("np.multiply(arr8, arr9):", np.multiply(arr8, arr9))

# Element-wise division of two arrays.
print("np.divide(arr8, arr9):", np.divide(arr8, arr9))

# Compute the square root of each element.
print("np.sqrt(arr8):", np.sqrt(arr8))

# Compute the exponential of each element.
print("np.exp(arr8):", np.exp(arr8))

# Compute the natural logarithm of each element.
print("np.log(arr8):", np.log(arr8))

Mathematical Operations:
arr8 + 5: [15 25 35]
arr8 - 5: [ 5 15 25]
arr8 * 2: [20 40 60]
arr8 / 2: [ 5. 10. 15.]
np.add(arr8, arr9): [11 22 33]
np.subtract(arr8, arr9): [ 9 18 27]
np.multiply(arr8, arr9): [10 40 90]
np.divide(arr8, arr9): [10. 10. 10.]
np.sqrt(arr8): [3.16227766 4.47213595 5.47722558]
np.exp(arr8): [2.20264658e+04 4.85165195e+08 1.06864746e+13]
np.log(arr8): [2.30258509 2.99573227 3.40119738]


In [140]:
# Statistical Operations
print("Statistical Operations:")

# Compute the mean of the array.
print("np.mean(arr8):", np.mean(arr8))

# Compute the median of the array.
print("np.median(arr8):", np.median(arr8))

# Compute the standard deviation.
print("np.std(arr8):", np.std(arr8))

# Compute the variance.
print("np.var(arr8):", np.var(arr8))

# Find the minimum value.
print("np.min(arr8):", np.min(arr8))

# Find the maximum value.
print("np.max(arr8):", np.max(arr8))

# Compute the sum of all elements.
print("np.sum(arr8):", np.sum(arr8))

# Compute the product of all elements.
print("np.prod(arr8):", np.prod(arr8))

Statistical Operations:
np.mean(arr8): 20.0
np.median(arr8): 20.0
np.std(arr8): 8.16496580927726
np.var(arr8): 66.66666666666667
np.min(arr8): 10
np.max(arr8): 30
np.sum(arr8): 60
np.prod(arr8): 6000


In [141]:
# Aggregation
arr10 = np.array([1, 2, 3, 4])
print("Aggregation:")

# Compute the cumulative sum
print("np.cumsum(arr10):", np.cumsum(arr10))

# Compute the cumulative product
print("np.cumprod(arr10):", np.cumprod(arr10))

Aggregation:
np.cumsum(arr10): [ 1  3  6 10]
np.cumprod(arr10): [ 1  2  6 24]


In [142]:
# Logical Operations
print("Logical Operations:")

# Element-wise comparison
print("arr8 > 15:", arr8 > 15)

# Return elements chosen from x or y depending on condition.
print("np.where(arr8 > 15, 'Yes', 'No'):", np.where(arr8 > 15, 'Yes', 'No'))

Logical Operations:
arr8 > 15: [False  True  True]
np.where(arr8 > 15, 'Yes', 'No'): ['No' 'Yes' 'Yes']


In [143]:
# Sorting and Searching
arr11 = np.array([3, 1, 2])
print("Sorting and Searching:")

# Return a sorted copy of the array
print("np.sort(arr11):", np.sort(arr11))

# Return indices that would sort the array
print("np.argsort(arr11):", np.argsort(arr11))

# Find indices where elements should be inserted to maintain order
print("np.searchsorted(arr11, 2):", np.searchsorted(arr11, 2))

Sorting and Searching:
np.sort(arr11): [1 2 3]
np.argsort(arr11): [1 2 0]
np.searchsorted(arr11, 2): 2


In [144]:
# Array Operations
arr12 = np.array([1, 2, 3])
arr13 = np.array([4, 5, 6])
print("Array Operations:")

# Concatenate arrays along a specified axis
print("np.concatenate([arr12, arr13]):", np.concatenate([arr12, arr13]))

# Stack arrays vertically
print("np.vstack([arr12, arr13]):\n", np.vstack([arr12, arr13]))

# Stack arrays horizontally
print("np.hstack([arr12, arr13]):", np.hstack([arr12, arr13]))

# Split the array into multiple sub-arrays
print("np.split(arr13, 3):", np.split(arr13, 3))

Array Operations:
np.concatenate([arr12, arr13]): [1 2 3 4 5 6]
np.vstack([arr12, arr13]):
 [[1 2 3]
 [4 5 6]]
np.hstack([arr12, arr13]): [1 2 3 4 5 6]
np.split(arr13, 3): [array([4]), array([5]), array([6])]


In [145]:
# Broadcasting: Operations between arrays of different shapes, where numpy automatically adjusts the shapes to perform the operation.
arr14 = np.array([1, 2, 3])
arr15 = np.array([[1], [2], [3]])
print("Broadcasting:")
print("arr14 + 10:\n", arr14 + 10)
print("arr15 + arr14:\n", arr15 + arr14)

Broadcasting:
arr14 + 10:
 [11 12 13]
arr15 + arr14:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [146]:
# Matrix Operations (for 2D arrays)
arr16 = np.array([[1, 2], [3, 4]])
arr17 = np.array([[5, 6], [7, 8]])
print("Matrix Operations:")

# Matrix multiplication.
print("np.dot(arr16, arr17):\n", np.dot(arr16, arr17))

# Matrix product
print("np.matmul(arr16, arr17):\n", np.matmul(arr16, arr17))

# Compute the inverse of a matrix
print("np.linalg.inv(arr16):\n", np.linalg.inv(arr16))

# Compute the determinant of a matrix
print("np.linalg.det(arr16):", np.linalg.det(arr16))

# Compute the eigenvalues and eigenvectors of a matrix
print("np.linalg.eig(arr16):\n", np.linalg.eig(arr16))

Matrix Operations:
np.dot(arr16, arr17):
 [[19 22]
 [43 50]]
np.matmul(arr16, arr17):
 [[19 22]
 [43 50]]
np.linalg.inv(arr16):
 [[-2.   1. ]
 [ 1.5 -0.5]]
np.linalg.det(arr16): -2.0000000000000004
np.linalg.eig(arr16):
 (array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [147]:
# Copy and View
arr18 = np.array([1, 2, 3])
arr19 = arr18.copy()
arr20 = arr18.view().reshape(3,1)
print("Copy and View:")

# Create a copy of the array.
print("arr19 (copy):", arr19)

# Create a view of the array with the same data but different shape or type
print("arr20 (view):\n", arr20)

Copy and View:
arr19 (copy): [1 2 3]
arr20 (view):
 [[1]
 [2]
 [3]]


In [148]:
# Modifying Elements
# Assign new values to elements using their index.
print("Original array:", arr)

arr[0] = 1
arr[1] = 2
arr[-1] = 9

print("After Modifications:", arr)

Original array: [10 20 30 40 50 60 70 80 90]
After Modifications: [ 1  2 30 40 50 60 70 80  9]


In [149]:
# Finding the Length:
# Use the len() function to determine the number of elements.
print(len(arr))

9


In [150]:
# Traversing an Array:
# Iterate through elements using a for loop.
for i in arr:
    print(i)

1
2
30
40
50
60
70
80
9


In [151]:
# Inserting an Element:
# Use the append() method to add an element at the end.
# Use insert() to insert at a specific index.
num = [1, 2, 3, 4, 5]

arr1 = np.array(num)
print("Original array:", arr1)

arr1 = np.append(arr1,6)
print("After append:", arr1)

arr1 = np.insert(arr1, 0, 0)
print("After insert:", arr1)

Original array: [1 2 3 4 5]
After append: [1 2 3 4 5 6]
After insert: [0 1 2 3 4 5 6]


In [152]:
# Deleting an Element:
# Use delete to delete an element at a specific index.

num = [1, 2, 3, 4, 5]
arr2 = np.array(num)

print("Original array:", arr2)

arr2 = np.delete(arr2, 2)
print("After deletion:", arr2)

Original array: [1 2 3 4 5]
After deletion: [1 2 4 5]


In [153]:
# find the index of first occurrence
arr3 = np.array([1, 2, 3, 4, 5])

indices = np.where(arr3 == 3)[0]

print(indices[0])

# np.where(arr == value_to_find) returns a tuple with one array of indices where the condition (arr == value_to_find) is True.
# [0] accesses the first array from the tuple returned by np.where.
# indices[0] gives you the first index of the occurrence.
# If the value is not found, indices will be an empty array, and you should handle that case to avoid errors.

2


In [154]:
# reverse
arr4 = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr = arr4[::-1]

print(reversed_arr)

[5 4 3 2 1]


In [155]:
# extend
# NumPy arrays are fixed-size once created, meaning you can't directly "extend" an array like you can with Python lists. 
# However, you can achieve a similar result by creating a new array with the desired size and copying the original data into it.

arr5 = np.array([1, 2, 3])

# Elements to append
new_elements = np.array([4, 5])

# Append elements
extended_arr = np.append(arr5, new_elements)

print(extended_arr)

[1 2 3 4 5]
