### Numpy:

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

#### What is an array?

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
# import the numpy package
import numpy as np

In [2]:
my_lst = [1, 2, 3, 4, 5]

In [3]:
arr = np.array(my_lst)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [4]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [5]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [6]:
# check the shape of the array

arr.shape

(3, 5)

In [7]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])